/**
 * Generate the KerbClock equivalence fixture: the same calendar data the TypeScript resolver
 * uses, plus 1,000 deterministic pseudo-random timestamps with the resolver's answers.
 * The Foundry test loads this, configures the contract from it, and must agree on every row.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { MARKETS, segmentAt, transitions, type SessionKind } from "../src/index.js";
import type { MarketCode } from "@kerb/types";

const MARKET_LIST: MarketCode[] = ["XNYS", "XHKG"];
const KIND: Record<SessionKind, number> = { CLOSED: 0, LUNCH: 1, PRE: 2, POST: 3, REGULAR: 4 };
const TRANSITION: Record<string, number> = {
  NONE: 0, PRE_OPEN: 1, SESSION_OPEN: 2, LUNCH_BREAK: 3, LUNCH_END: 4, SESSION_CLOSE: 5, EARLY_CLOSE: 6, POST_CLOSE: 7,
  SESSION_BREAK: 0, SESSION_END: 0,
};
const hm = (s: string): number => {
  const [h, m] = s.split(":").map(Number) as [number, number];
  return h * 60 + m;
};
const dayNumber = (d: string): number => Math.floor(Date.parse(`${d}T00:00:00Z`) / 86_400_000);

/** Deterministic PRNG so the fixture is reproducible. */
function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const weeklyFlat: number[] = [];
const overrideDays: number[] = [];
const overrideFlat: number[] = [];
const marketsFlat: number[] = [];

for (let mi = 0; mi < MARKET_LIST.length; mi++) {
  const code = MARKET_LIST[mi] as MarketCode;
  const spec = MARKETS[code];
  const isUs = spec.tz === "America/New_York";
  // base (standard) offset in minutes, DST rule, DST offset, coverage
  marketsFlat.push(mi, isUs ? -300 : 480, isUs ? 1 : 0, isUs ? 60 : 0, dayNumber("2025-12-01"), dayNumber("2027-12-31"), spec.defaultCureWindowSec);
  for (let dow = 0; dow < 7; dow++) {
    for (const s of spec.weekly[dow] ?? []) weeklyFlat.push(mi, dow, hm(s.start), hm(s.end), KIND[s.kind]);
  }
  for (const [date, o] of Object.entries(spec.overrides)) {
    const d = dayNumber(date);
    overrideDays.push(mi, d);
    for (const s of o.sessions) overrideFlat.push(mi, d, hm(s.start), hm(s.end), KIND[s.kind]);
  }
}

const rnd = mulberry32(20260920);
const from = Date.parse("2026-01-05T00:00:00Z") / 1000;
const to = Date.parse("2027-06-30T00:00:00Z") / 1000;
const cases: number[] = [];
let n = 0;
while (n < 1000) {
  const mi = n % MARKET_LIST.length;
  const code = MARKET_LIST[mi] as MarketCode;
  // Half uniformly random, half near a transition where the two implementations must agree exactly.
  let ts: number;
  if (n % 2 === 0) {
    ts = Math.floor(from + rnd() * (to - from));
  } else {
    const anchor = Math.floor(from + rnd() * (to - from));
    const t = transitions(code, anchor * 1000)[0];
    if (!t) continue;
    ts = Math.floor(t.atMs / 1000) + Math.floor(rnd() * 121) - 60;
  }
  if (ts < from || ts > to) continue;
  const seg = segmentAt(code, ts * 1000);
  const next = transitions(code, ts * 1000)[0];
  const weak = transitions(code, ts * 1000).find((x) => x.from === "REGULAR");
  if (!next || !weak) continue;
  const cureSec = MARKETS[code].defaultCureWindowSec;
  const opensAt = Math.floor(weak.atMs / 1000) - cureSec;
  const cureOpen = ts >= opensAt && ts < Math.floor(weak.atMs / 1000) ? 1 : 0;
  cases.push(mi, ts, KIND[seg.kind], TRANSITION[next.type] ?? 0, Math.floor(next.atMs / 1000), TRANSITION[weak.type] ?? 0, Math.floor(weak.atMs / 1000), cureOpen);
  n++;
}

const out = resolve(dirname(fileURLToPath(import.meta.url)), "../../../data/fixtures/clock");
mkdirSync(out, { recursive: true });
writeFileSync(resolve(out, "equivalence.json"), `${JSON.stringify({
  note: "Generated by packages/calendar/scripts/equivalence-fixture.ts. Markets: 0=XNYS, 1=XHKG.",
  calendarVersion: MARKETS.XNYS.sourceNote.slice(0, 0) + "kerb-calendar@0.1.0",
  marketsFlat, weeklyFlat, overrideDays, overrideFlat, cases,
}, null, 1)}\n`);
console.log(`markets ${marketsFlat.length / 7}, weekly rows ${weeklyFlat.length / 5}, override days ${overrideDays.length / 2}, override rows ${overrideFlat.length / 5}, cases ${cases.length / 8}`);
console.log(`ts range ${new Date(from * 1000).toISOString()} .. ${new Date(to * 1000).toISOString()}`);
