// PM2 process file. Secrets are NOT here: they are loaded from an env file outside the repo.
const envFile = process.env.KERB_ENV_FILE || "/root/.kerb/collector.env";

module.exports = {
  apps: [
    {
      name: "kerb-collector",
      cwd: __dirname + "/apps/collector",
      script: "src/main.ts",
      interpreter: "node",
      interpreter_args: `--env-file=${envFile} --import tsx`,
      autorestart: true,
      restart_delay: 5000,
      exp_backoff_restart_delay: 2000,
      max_restarts: 1000,
      min_uptime: 20000,
      kill_timeout: 8000,
      max_memory_restart: "600M",
      time: true,
      out_file: "/root/.kerb/logs/collector.out.log",
      error_file: "/root/.kerb/logs/collector.err.log",
    },
    {
      name: "kerb-attester",
      cwd: __dirname + "/apps/attester",
      script: "src/main.ts",
      interpreter: "node",
      interpreter_args: `--env-file=${process.env.KERB_ATTESTER_ENV_FILE || "/root/.kerb/attester.env"} --import tsx`,
      autorestart: true,
      restart_delay: 15000,
      exp_backoff_restart_delay: 5000,
      max_restarts: 200,
      min_uptime: 60000,
      kill_timeout: 20000,
      max_memory_restart: "700M",
      time: true,
      out_file: "/root/.kerb/logs/attester.out.log",
      error_file: "/root/.kerb/logs/attester.err.log",
    },
    {
      name: "kerb-attester-mainnet",
      cwd: __dirname + "/apps/attester",
      script: "src/main.ts",
      interpreter: "node",
      interpreter_args: `--env-file=${process.env.KERB_ATTESTER_MAINNET_ENV_FILE || "/root/.kerb/attester-mainnet.env"} --import tsx`,
      autorestart: true,
      restart_delay: 15000,
      exp_backoff_restart_delay: 5000,
      max_restarts: 200,
      min_uptime: 60000,
      kill_timeout: 20000,
      max_memory_restart: "700M",
      time: true,
      out_file: "/root/.kerb/logs/attester-mainnet.out.log",
      error_file: "/root/.kerb/logs/attester-mainnet.err.log",
    },
    {
      name: "kerb-api",
      cwd: __dirname + "/apps/api",
      script: "src/main.ts",
      interpreter: "node",
      interpreter_args: `--env-file=${process.env.KERB_API_ENV_FILE || "/root/.kerb/api.env"} --import tsx`,
      autorestart: true,
      restart_delay: 10000,
      exp_backoff_restart_delay: 3000,
      max_restarts: 300,
      min_uptime: 30000,
      kill_timeout: 15000,
      max_memory_restart: "700M",
      time: true,
      out_file: "/root/.kerb/logs/api.out.log",
      error_file: "/root/.kerb/logs/api.err.log",
    },
    {
      // Live site. Served from a release directory, never from this checkout: scripts/deploy-web.sh
      // builds each release in its own worktree and swaps `current` only after it answers.
      name: "kerb-web",
      cwd: "/root/kerb-deploy/live/current/apps/web",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3300",
      interpreter: "node",
      interpreter_args: `--env-file=${process.env.KERB_WEB_ENV_FILE || "/root/.kerb/web.env"}`,
      autorestart: true,
      restart_delay: 5000,
      exp_backoff_restart_delay: 2000,
      max_restarts: 300,
      min_uptime: 20000,
      kill_timeout: 10000,
      max_memory_restart: "700M",
      time: true,
      out_file: "/root/.kerb/logs/web.out.log",
      error_file: "/root/.kerb/logs/web.err.log",
    },
    {
      // V2 staging at v2.usekerb.xyz. Same app, same public API, its own release directory.
      name: "kerb-web-v2",
      cwd: "/root/kerb-deploy/staging/current/apps/web",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3301",
      interpreter: "node",
      interpreter_args: `--env-file=${process.env.KERB_WEB_V2_ENV_FILE || "/root/.kerb/web-v2.env"}`,
      autorestart: true,
      restart_delay: 5000,
      exp_backoff_restart_delay: 2000,
      max_restarts: 300,
      min_uptime: 20000,
      kill_timeout: 10000,
      max_memory_restart: "700M",
      time: true,
      out_file: "/root/.kerb/logs/web-v2.out.log",
      error_file: "/root/.kerb/logs/web-v2.err.log",
    },
    {
      name: "kerb-mirror-relay",
      cwd: __dirname + "/apps/attester",
      script: "scripts/relay-mirrors.ts",
      interpreter: "node",
      interpreter_args: `--env-file=${process.env.KERB_MIRROR_ENV_FILE || "/root/.kerb/mirror-relay.env"} --import tsx`,
      autorestart: true,
      restart_delay: 30000,
      exp_backoff_restart_delay: 5000,
      max_restarts: 200,
      min_uptime: 60000,
      kill_timeout: 20000,
      max_memory_restart: "700M",
      time: true,
      out_file: "/root/.kerb/logs/mirror-relay.out.log",
      error_file: "/root/.kerb/logs/mirror-relay.err.log",
    },
    {
      // First-paint freshness (V3-01, L-01): keeps every live ISR route regenerating.
      name: "kerb-web-warmer",
      cwd: __dirname,
      script: "scripts/web-warmer.ts",
      interpreter: "node",
      interpreter_args: "--import tsx",
      env: { KERB_WARM_BASE: "http://127.0.0.1:3300", KERB_WARM_HOST: "www.usekerb.xyz", KERB_API_INTERNAL: "http://127.0.0.1:8720" },
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 100,
      min_uptime: 30000,
      max_memory_restart: "200M",
      time: true,
      out_file: "/root/.kerb/logs/web-warmer.out.log",
      error_file: "/root/.kerb/logs/web-warmer.err.log",
    },
    {
      // Demo position keeper (V2-08, gate 6). Testnet only. Not started until the operator approves:
      //   pm2 start ecosystem.config.cjs --only kerb-demo-keeper && pm2 save
      name: "kerb-demo-keeper",
      cwd: __dirname + "/apps/attester",
      script: "scripts/demo-keeper.ts",
      interpreter: "node",
      interpreter_args: `--env-file=${process.env.KERB_KEEPER_ENV_FILE || "/root/.kerb/keeper.env"} --import tsx`,
      autorestart: true,
      restart_delay: 30000,
      max_restarts: 50,
      min_uptime: 60000,
      max_memory_restart: "400M",
      time: true,
      out_file: "/root/.kerb/logs/keeper.out.log",
      error_file: "/root/.kerb/logs/keeper.err.log",
    },
    {
      name: "kerb-indexer",
      cwd: __dirname + "/apps/indexer",
      script: "src/main.ts",
      interpreter: "node",
      interpreter_args: `--env-file=${process.env.KERB_INDEXER_ENV_FILE || "/root/.kerb/indexer.env"} --import tsx`,
      autorestart: true,
      restart_delay: 10000,
      exp_backoff_restart_delay: 3000,
      max_restarts: 300,
      min_uptime: 30000,
      kill_timeout: 15000,
      max_memory_restart: "700M",
      time: true,
      out_file: "/root/.kerb/logs/indexer.out.log",
      error_file: "/root/.kerb/logs/indexer.err.log",
    },
  ],
};
